[package]
name = "rosa-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
slab = "0.4.12"

rosa-protocol.workspace = true
rosa-map.workspace = true
rosa-math.workspace = true
rosa-physics.workspace = true

glam.workspace = true
rand.workspace = true
tokio.workspace = true

[lints]
workspace = true