[workspace]
resolver="3"
members = ["crates/rosa-bin", "crates/rosa-map","crates/rosa-math", "crates/rosa-net", "crates/rosa-physics", "crates/rosa-protocol", "crates/rosa-sim"]

[workspace.lints.clippy]
neg_cmp_op_on_partial_ord = "allow"
approx_constant = "allow"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.229", features = [ "derive" ] }
# hecs = "0.11.2"
glam = "0.34.1"
binrw = "0.15.0"

rosa-map = { path = "crates/rosa-map", default-features = false }
rosa-sim = { path = "crates/rosa-sim", default-features = false }
rosa-math = { path = "crates/rosa-math", default-features = false }
rosa-net = { path = "crates/rosa-net", default-features = false }
rosa-protocol = { path = "crates/rosa-protocol", default-features = false }
rosa-physics = { path = "crates/rosa-physics", default-features = false }