master_server_url = "www.crypticsea.com"
port = 27584
map_name = "round"
server_name = "Rosa but not rosa"
admin_password = "admin"
server_password = "test"
gamemode = "Sandbox"
max_players = 16
round_time = 300
voice_chat = false
voice_min = 1000
voice_boost = 0
help = true
manual_hands = false
